CREATE SEQUENCE SEQ_FILE;
CREATE TABLE TBL_FILE(
    ID NUMBER CONSTRAINT PK_FILE PRIMARY KEY,
    FILE_NAME VARCHAR2(1000) NOT NULL,
    FILE_SIZE VARCHAR2(1000) NOT NULL,
    FILE_PATH VARCHAR2(1000) NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_FILE;
SELECT * FROM TBL_POST_FILE;
CREATE TABLE TBL_POST_FILE(
    ID NUMBER CONSTRAINT PK_POST_FILE PRIMARY KEY,
    POST_ID NUMBER NOT NULL,
    FILE_TYPE VARCHAR2(1000) DEFAULT 'IMAGE',
    CONSTRAINT FK_POST_FILE_FILE FOREIGN KEY(ID)
    REFERENCES TBL_FILE(ID),
    CONSTRAINT FK_POST_FILE_POST FOREIGN KEY(POST_ID)
    REFERENCES TBL_POST(ID) ON DELETE CASCADE
);

SELECT * FROM TBL_FILE;
SELECT * FROM TBL_POST_FILE;

CREATE OR REPLACE VIEW VIEW_POST_POST_FILE AS
(
    SELECT F.ID, FILE_NAME, FILE_SIZE, FILE_PATH, CREATED_DATE, UPDATED_DATE, POST_ID, FILE_TYPE
    FROM TBL_FILE F JOIN TBL_POST_FILE PF
    ON F.ID = PF.ID
);
