SELECT * FROM TBL_MEMBER M JOIN TBL_POST P
ON M.ID = P.MEMBER_ID AND M.MEMBER_NAME IN('홍길동', 'test');


SELECT
    MEMBER_NAME, ID, POST_TITLE, POST_CONTENT,
    POST_READ_COUNT, MEMBER_ID, CREATED_DATE, UPDATED_DATE
FROM
(
    SELECT
        ROWNUM R, MEMBER_NAME, ID, POST_TITLE, POST_CONTENT,
        POST_READ_COUNT, MEMBER_ID, CREATED_DATE, UPDATED_DATE
        FROM
            (
                SELECT
                    M.MEMBER_NAME, P.ID, P.POST_TITLE, P.POST_CONTENT,
                    P.POST_READ_COUNT, P.MEMBER_ID, P.CREATED_DATE, P.UPDATED_DATE
                FROM TBL_MEMBER M JOIN TBL_POST P
                ON M.ID = P.MEMBER_ID
                ORDER BY ID DESC
            )
        WHERE ROWNUM <= 10
)
WHERE R >= 1;
