CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
    ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(1000) NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    POST_ID NUMBER NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
    REFERENCES TBL_MEMBER(ID),
    CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
    REFERENCES TBL_POST(ID)
);

SELECT * FROM TBL_REPLY;

CREATE OR REPLACE VIEW VIEW_REPLY_MEMBER AS
(
    SELECT
        M.MEMBER_NAME, R.ID, R.REPLY_CONTENT,
        R.MEMBER_ID, R.POST_ID, R.CREATED_DATE, R.UPDATED_DATE
    FROM TBL_MEMBER M JOIN TBL_REPLY R
    ON M.ID = R.MEMBER_ID
);

SELECT * FROM VIEW_REPLY_MEMBER;

INSERT INTO TBL_REPLY (ID, REPLY_CONTENT, MEMBER_ID, POST_ID)
VALUES(SEQ_REPLY.NEXTVAL, '테스트 댓글 20', 101, 10441);
















