server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: scott
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.tedhan
    password: mkfa pzal xyaw gooa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 40MB
      max-file-size: 10MB
      file-size-threshold: 100MB

mybatis:
  config-location: classpath:/config/config.xml
  mapper-locations: classpath*:/mapper/*.xml
