SELECT * FROM TBL_POST;

SELECT
    P.ID, P.POST_TITLE, P.POST_CONTENT, P.POST_READ_COUNT,
    P.MEMBER_ID, P.CREATED_DATE, P.UPDATED_DATE, P.MEMBER_NAME
FROM
    (
        SELECT ROWNUM R,
               P.ID, P.POST_TITLE, P.POST_CONTENT, P.POST_READ_COUNT,
               P.MEMBER_ID, P.CREATED_DATE, P.UPDATED_DATE, M.MEMBER_NAME
        FROM TBL_MEMBER M JOIN TBL_POST P
        ON M.ID = P.MEMBER_ID AND ROWNUM <= 80
        ORDER BY P.ID DESC
    ) P
WHERE P.R >= 71;